### 第 9）获取条目详情
GET http://127.0.0.1:8000/api/tasks/get-item-detail?task=2&itemID=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0ODQ4OTY3LCJpYXQiOjE3NjQ4NDUzNjcsImp0aSI6ImUwMjlmOWYxNzQ2YzQ2YzNiMWZmZTdlOWI3Y2E5YTcwIiwidXNlcl9pZCI6IjEifQ.-zMrl5IE2g6m4F4CgnAA5uRtTTz9b7ZVRrTiXr4euo4
