POST http://127.0.0.1:8000/api/tasks/run-task/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MzgzMzUwLCJpYXQiOjE3NjYzNzk3NTAsImp0aSI6IjYzMDNkMjY4OGRhNjQ3OTFhN2JhYzA2MmMyMDYyOWNjIiwidXNlcl9pZCI6IjEifQ.Zg3WE9CpxlZzX6b3_H3d0sAkk6wvO61Lmgkw5WjsSHs
Content-Type: application/json

{
  "task_id":4
}